# Generated by Django 4.0.3 on 2022-03-10 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_user_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Otp',
        ),
    ]
